### PR TITLE
Add an indexType field to `SnapshotMetadata` and `ReplicaMetadata`

### PR DESCRIPTION
**Pull request by mansu**
Add an indexType field to `SnapshotMetadata` and `ReplicaMetadata` to encode the type of index used in replica and snapshots.

### CODE REVIEW

**Comment by vthacker** [comment]
What's the motivation for this PR?

**Comment by mansu** [comment]
When we use NRTSearch, we want to store it as a different type of index if needed. This change will also lay the ground work for supporting different chunk types in the future.

**Comment by mansu** [comment]
> What's the motivation for this PR?

When we use NRTSearch, we want to store it as a different type of index if needed. This change will also lay the ground work for supporting different chunk types in the future.

**Comment by vthacker** [comment]
> > What's the motivation for this PR?
> 
> When we use NRTSearch, we want to store it as a different type of index if needed. This change will also lay the ground work for supporting different chunk types in the future.

If we do this PR, I'd like us not to use `LUCENE_REGULAR` and add the version of lucene being used to create it.

Secondly, what's the plan to match the index type version when we download an index to the cache node?

**Comment by mansu** [comment]
> > > What's the motivation for this PR?
> > 
> > 
> > When we use NRTSearch, we want to store it as a different type of index if needed. This change will also lay the ground work for supporting different chunk types in the future.
> 
> If we do this PR, I'd like us not to use `LUCENE_REGULAR` and add the version of lucene being used to create it.
> 
Changed it to `LOGS_LUCENE9`
> Secondly, what's the plan to match the index type version when we download an index to the cache node?
That's the next step. Once the replica metadata has these fields, we can match the cache nodes with the snapshot type during assignment.

**Pull request merged**
